// Code generated by MockGen. DO NOT EDIT.
// Source: server/domain (interfaces: ClassroomUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	postgresql "server/database/postgresql"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockClassroomUsecase is a mock of ClassroomUsecase interface.
type MockClassroomUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockClassroomUsecaseMockRecorder
}

// MockClassroomUsecaseMockRecorder is the mock recorder for MockClassroomUsecase.
type MockClassroomUsecaseMockRecorder struct {
	mock *MockClassroomUsecase
}

// NewMockClassroomUsecase creates a new mock instance.
func NewMockClassroomUsecase(ctrl *gomock.Controller) *MockClassroomUsecase {
	mock := &MockClassroomUsecase{ctrl: ctrl}
	mock.recorder = &MockClassroomUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassroomUsecase) EXPECT() *MockClassroomUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClassroomUsecase) Create(arg0 context.Context, arg1 *postgresql.CreateClassParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClassroomUsecaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClassroomUsecase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockClassroomUsecase) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClassroomUsecaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClassroomUsecase)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockClassroomUsecase) GetByID(arg0 context.Context, arg1 uuid.UUID) (postgresql.Classroom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(postgresql.Classroom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClassroomUsecaseMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClassroomUsecase)(nil).GetByID), arg0, arg1)
}

// GetByInviteCode mocks base method.
func (m *MockClassroomUsecase) GetByInviteCode(arg0 context.Context, arg1 uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteCode", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteCode indicates an expected call of GetByInviteCode.
func (mr *MockClassroomUsecaseMockRecorder) GetByInviteCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteCode", reflect.TypeOf((*MockClassroomUsecase)(nil).GetByInviteCode), arg0, arg1)
}

// GetClasroomsByUser mocks base method.
func (m *MockClassroomUsecase) GetClasroomsByUser(arg0 context.Context, arg1 postgresql.GetAllClassFromUserParams) ([]postgresql.Classroom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClasroomsByUser", arg0, arg1)
	ret0, _ := ret[0].([]postgresql.Classroom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClasroomsByUser indicates an expected call of GetClasroomsByUser.
func (mr *MockClassroomUsecaseMockRecorder) GetClasroomsByUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClasroomsByUser", reflect.TypeOf((*MockClassroomUsecase)(nil).GetClasroomsByUser), arg0, arg1)
}

// GetClassroomMembers mocks base method.
func (m *MockClassroomUsecase) GetClassroomMembers(arg0 context.Context, arg1 uuid.UUID) ([]postgresql.ClassroomMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClassroomMembers", arg0, arg1)
	ret0, _ := ret[0].([]postgresql.ClassroomMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClassroomMembers indicates an expected call of GetClassroomMembers.
func (mr *MockClassroomUsecaseMockRecorder) GetClassroomMembers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClassroomMembers", reflect.TypeOf((*MockClassroomUsecase)(nil).GetClassroomMembers), arg0, arg1)
}

// UpdateClassroomDescription mocks base method.
func (m *MockClassroomUsecase) UpdateClassroomDescription(arg0 context.Context, arg1 *postgresql.UpdateClassroomDescriptionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassroomDescription", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClassroomDescription indicates an expected call of UpdateClassroomDescription.
func (mr *MockClassroomUsecaseMockRecorder) UpdateClassroomDescription(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassroomDescription", reflect.TypeOf((*MockClassroomUsecase)(nil).UpdateClassroomDescription), arg0, arg1)
}

// UpdateClassroomInviteCode mocks base method.
func (m *MockClassroomUsecase) UpdateClassroomInviteCode(arg0 context.Context, arg1 *postgresql.UpdateClassroomInviteCodeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassroomInviteCode", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClassroomInviteCode indicates an expected call of UpdateClassroomInviteCode.
func (mr *MockClassroomUsecaseMockRecorder) UpdateClassroomInviteCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassroomInviteCode", reflect.TypeOf((*MockClassroomUsecase)(nil).UpdateClassroomInviteCode), arg0, arg1)
}

// UpdateClassroomName mocks base method.
func (m *MockClassroomUsecase) UpdateClassroomName(arg0 context.Context, arg1 *postgresql.UpdateClassroomNameParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassroomName", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClassroomName indicates an expected call of UpdateClassroomName.
func (mr *MockClassroomUsecaseMockRecorder) UpdateClassroomName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassroomName", reflect.TypeOf((*MockClassroomUsecase)(nil).UpdateClassroomName), arg0, arg1)
}

// UpdateClassroomRoom mocks base method.
func (m *MockClassroomUsecase) UpdateClassroomRoom(arg0 context.Context, arg1 *postgresql.UpdateClassroomRoomParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassroomRoom", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClassroomRoom indicates an expected call of UpdateClassroomRoom.
func (mr *MockClassroomUsecaseMockRecorder) UpdateClassroomRoom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassroomRoom", reflect.TypeOf((*MockClassroomUsecase)(nil).UpdateClassroomRoom), arg0, arg1)
}

// UpdateClassroomSection mocks base method.
func (m *MockClassroomUsecase) UpdateClassroomSection(arg0 context.Context, arg1 *postgresql.UpdateClassroomSectionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassroomSection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClassroomSection indicates an expected call of UpdateClassroomSection.
func (mr *MockClassroomUsecaseMockRecorder) UpdateClassroomSection(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassroomSection", reflect.TypeOf((*MockClassroomUsecase)(nil).UpdateClassroomSection), arg0, arg1)
}

// UpdateClassroomSubject mocks base method.
func (m *MockClassroomUsecase) UpdateClassroomSubject(arg0 context.Context, arg1 *postgresql.UpdateClassroomSubjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClassroomSubject", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClassroomSubject indicates an expected call of UpdateClassroomSubject.
func (mr *MockClassroomUsecaseMockRecorder) UpdateClassroomSubject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClassroomSubject", reflect.TypeOf((*MockClassroomUsecase)(nil).UpdateClassroomSubject), arg0, arg1)
}
