// Code generated by MockGen. DO NOT EDIT.
// Source: server/domain (interfaces: RefreshTokenUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	tokenutil "server/internal/tokenutil"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRefreshTokenUsecase is a mock of RefreshTokenUsecase interface.
type MockRefreshTokenUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenUsecaseMockRecorder
}

// MockRefreshTokenUsecaseMockRecorder is the mock recorder for MockRefreshTokenUsecase.
type MockRefreshTokenUsecaseMockRecorder struct {
	mock *MockRefreshTokenUsecase
}

// NewMockRefreshTokenUsecase creates a new mock instance.
func NewMockRefreshTokenUsecase(ctrl *gomock.Controller) *MockRefreshTokenUsecase {
	mock := &MockRefreshTokenUsecase{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenUsecase) EXPECT() *MockRefreshTokenUsecaseMockRecorder {
	return m.recorder
}

// CreateAccessToken mocks base method.
func (m *MockRefreshTokenUsecase) CreateAccessToken(arg0 string, arg1 time.Duration) (string, *tokenutil.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*tokenutil.Payload)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAccessToken indicates an expected call of CreateAccessToken.
func (mr *MockRefreshTokenUsecaseMockRecorder) CreateAccessToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessToken", reflect.TypeOf((*MockRefreshTokenUsecase)(nil).CreateAccessToken), arg0, arg1)
}

// ValidateRefreshToken mocks base method.
func (m *MockRefreshTokenUsecase) ValidateRefreshToken(arg0 string) (*tokenutil.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", arg0)
	ret0, _ := ret[0].(*tokenutil.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockRefreshTokenUsecaseMockRecorder) ValidateRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockRefreshTokenUsecase)(nil).ValidateRefreshToken), arg0)
}
