basePath: /
consumes:
    - application/json
definitions:
    Role:
        type: string
        x-go-package: server/database/sqlc
    User:
        properties:
            created_at:
                format: date-time
                type: string
                x-go-name: CreatedAt
            email:
                type: string
                x-go-name: Email
            id:
                format: uuid
                type: string
                x-go-name: ID
            updated_at:
                format: date-time
                type: string
                x-go-name: UpdatedAt
            user_role:
                $ref: '#/definitions/Role'
            username:
                type: string
                x-go-name: Username
            visibility:
                $ref: '#/definitions/Visibility'
        type: object
        x-go-package: server/database/sqlc
    Visibility:
        type: string
        x-go-package: server/database/sqlc
    authRequest:
        properties:
            password:
                description: |-
                    The password in the json body
                    in: body
                type: string
                uniqueItems: true
                x-go-name: Password
            username:
                description: The username in the json body
                type: string
                uniqueItems: true
                x-go-name: Username
        type: object
        x-go-package: server/routes
    authSuccessResponse:
        properties:
            access_token:
                description: The access token of response.
                type: string
                x-go-name: Access
            user:
                $ref: '#/definitions/User'
        required:
            - access_token
            - user
        type: object
        x-go-package: server/routes
host: localhost:5000
info:
    description: '# The purpose of this API is to query the Users'
    title: of User API.
    version: 1.0.0
paths:
    /api/v1/login:
        post:
            consumes:
                - application/json
            operationId: authUser
            parameters:
                - description: The json payload for login handler
                  in: body
                  name: body
                  required: true
                  schema:
                    $ref: '#/definitions/authRequest'
                  x-go-name: Body
            produces:
                - application/json
            responses:
                "200":
                    description: login success response
                    schema:
                        $ref: '#/definitions/authSuccessResponse'
                        type: object
            tags:
                - auth
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
