// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: class.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classrooms (id, admin_id, name, description, section, room, subject, invite_code, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, admin_id, name, description, section, room, subject, invite_code, visibility, created_at, updated_at
`

type CreateClassParams struct {
	ID          uuid.UUID  `json:"id"`
	AdminID     uuid.UUID  `json:"admin_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Section     string     `json:"section"`
	Room        string     `json:"room"`
	Subject     string     `json:"subject"`
	InviteCode  uuid.UUID  `json:"invite_code"`
	Visibility  Visibility `json:"visibility"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Classroom, error) {
	row := q.queryRow(ctx, q.createClassStmt, createClass,
		arg.ID,
		arg.AdminID,
		arg.Name,
		arg.Description,
		arg.Section,
		arg.Room,
		arg.Subject,
		arg.InviteCode,
		arg.Visibility,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Name,
		&i.Description,
		&i.Section,
		&i.Room,
		&i.Subject,
		&i.InviteCode,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :one
DELETE FROM classrooms
WHERE id = $1
RETURNING id, admin_id, name, description, section, room, subject, invite_code, visibility, created_at, updated_at
`

func (q *Queries) DeleteClass(ctx context.Context, id uuid.UUID) (Classroom, error) {
	row := q.queryRow(ctx, q.deleteClassStmt, deleteClass, id)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Name,
		&i.Description,
		&i.Section,
		&i.Room,
		&i.Subject,
		&i.InviteCode,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllClassFromUser = `-- name: GetAllClassFromUser :many
SELECT id, admin_id, name, description, section, room, subject, invite_code, visibility, created_at, updated_at
FROM classrooms
WHERE admin_id = $1
ORDER BY created_at
LIMIT 10
OFFSET $2
`

type GetAllClassFromUserParams struct {
	AdminID uuid.UUID `json:"admin_id"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetAllClassFromUser(ctx context.Context, arg GetAllClassFromUserParams) ([]Classroom, error) {
	rows, err := q.query(ctx, q.getAllClassFromUserStmt, getAllClassFromUser, arg.AdminID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Classroom
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Name,
			&i.Description,
			&i.Section,
			&i.Room,
			&i.Subject,
			&i.InviteCode,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClass = `-- name: GetClass :one
SELECT id, admin_id, name, description, section, room, subject, invite_code, visibility, created_at, updated_at
FROM classrooms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetClass(ctx context.Context, id uuid.UUID) (Classroom, error) {
	row := q.queryRow(ctx, q.getClassStmt, getClass, id)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Name,
		&i.Description,
		&i.Section,
		&i.Room,
		&i.Subject,
		&i.InviteCode,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPublicClass = `-- name: ListAllPublicClass :many
SELECT id, admin_id, name, description, section, room, subject, invite_code, visibility, created_at, updated_at
FROM classrooms
WHERE visibility = 'PUBLIC'
ORDER BY created_at
LIMIT 10
OFFSET $1
`

//description: List all classes
//parameters: none
//returns: classes
func (q *Queries) ListAllPublicClass(ctx context.Context, offset int32) ([]Classroom, error) {
	rows, err := q.query(ctx, q.listAllPublicClassStmt, listAllPublicClass, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Classroom
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Name,
			&i.Description,
			&i.Section,
			&i.Room,
			&i.Subject,
			&i.InviteCode,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE classrooms
SET name = $1, description = $2, section = $3, room = $4, subject = $5, invite_code = $6
WHERE id = $7
RETURNING id, admin_id, name, description, section, room, subject, invite_code, visibility, created_at, updated_at
`

type UpdateClassParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Section     string    `json:"section"`
	Room        string    `json:"room"`
	Subject     string    `json:"subject"`
	InviteCode  uuid.UUID `json:"invite_code"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Classroom, error) {
	row := q.queryRow(ctx, q.updateClassStmt, updateClass,
		arg.Name,
		arg.Description,
		arg.Section,
		arg.Room,
		arg.Subject,
		arg.InviteCode,
		arg.ID,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Name,
		&i.Description,
		&i.Section,
		&i.Room,
		&i.Subject,
		&i.InviteCode,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
