// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: class_work.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteClassworkFromClass = `-- name: DeleteClassworkFromClass :exec
DELETE FROM "class_work"
WHERE id = $1 AND user_id = $2 AND class_id = $3
`

type DeleteClassworkFromClassParams struct {
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
	ClassID uuid.UUID `json:"class_id"`
}

func (q *Queries) DeleteClassworkFromClass(ctx context.Context, arg DeleteClassworkFromClassParams) error {
	_, err := q.exec(ctx, q.deleteClassworkFromClassStmt, deleteClassworkFromClass, arg.ID, arg.UserID, arg.ClassID)
	return err
}

const getClassWork = `-- name: GetClassWork :one
SELECT id, name, user_id, class_id, mark, created_at, updated_at 
FROM "class_work" 
WHERE id = $1 AND user_id = $2 AND class_id = $3
`

type GetClassWorkParams struct {
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
	ClassID uuid.UUID `json:"class_id"`
}

//description: Get a class work by id
//parameters: id
//returns: class_work
func (q *Queries) GetClassWork(ctx context.Context, arg GetClassWorkParams) (ClassWork, error) {
	row := q.queryRow(ctx, q.getClassWorkStmt, getClassWork, arg.ID, arg.UserID, arg.ClassID)
	var i ClassWork
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.ClassID,
		&i.Mark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNewClasswork = `-- name: InsertNewClasswork :one
INSERT INTO "class_work" (
  id, name, user_id, class_id
) VALUES (
  $1, $2, $3, $4
) RETURNING id, name, user_id, class_id, mark, created_at, updated_at
`

type InsertNewClassworkParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	UserID  uuid.UUID `json:"user_id"`
	ClassID uuid.UUID `json:"class_id"`
}

func (q *Queries) InsertNewClasswork(ctx context.Context, arg InsertNewClassworkParams) (ClassWork, error) {
	row := q.queryRow(ctx, q.insertNewClassworkStmt, insertNewClasswork,
		arg.ID,
		arg.Name,
		arg.UserID,
		arg.ClassID,
	)
	var i ClassWork
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.ClassID,
		&i.Mark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClassworkAdmin = `-- name: ListClassworkAdmin :many
SELECT id, name, user_id, class_id, mark, created_at, updated_at
FROM "class_work"
WHERE class_id = $1
ORDER BY created_at
DESC
`

//description: List all class works
//parameters: none
//returns: class_work
func (q *Queries) ListClassworkAdmin(ctx context.Context, classID uuid.UUID) ([]ClassWork, error) {
	rows, err := q.query(ctx, q.listClassworkAdminStmt, listClassworkAdmin, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassWork
	for rows.Next() {
		var i ClassWork
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.ClassID,
			&i.Mark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmittedClassworks = `-- name: ListSubmittedClassworks :many
SELECT id, name, user_id, class_id, mark, created_at, updated_at
FROM "class_work"
WHERE class_id = $1 AND user_id = $2
ORDER BY created_at
DESC
`

type ListSubmittedClassworksParams struct {
	ClassID uuid.UUID `json:"class_id"`
	UserID  uuid.UUID `json:"user_id"`
}

//description: List all submitted classworks of a user
//parameters: user_id, class_id
//returns: class_work
func (q *Queries) ListSubmittedClassworks(ctx context.Context, arg ListSubmittedClassworksParams) ([]ClassWork, error) {
	rows, err := q.query(ctx, q.listSubmittedClassworksStmt, listSubmittedClassworks, arg.ClassID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassWork
	for rows.Next() {
		var i ClassWork
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.ClassID,
			&i.Mark,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAClassworkMark = `-- name: UpdateAClassworkMark :exec
UPDATE "class_work"
SET mark = $1
WHERE id = $2 AND user_id = $3 AND class_id = $4
`

type UpdateAClassworkMarkParams struct {
	Mark    sql.NullInt32 `json:"mark"`
	ID      uuid.UUID     `json:"id"`
	UserID  uuid.UUID     `json:"user_id"`
	ClassID uuid.UUID     `json:"class_id"`
}

func (q *Queries) UpdateAClassworkMark(ctx context.Context, arg UpdateAClassworkMarkParams) error {
	_, err := q.exec(ctx, q.updateAClassworkMarkStmt, updateAClassworkMark,
		arg.Mark,
		arg.ID,
		arg.UserID,
		arg.ClassID,
	)
	return err
}
