// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClass(ctx context.Context, arg CreateClassParams) (Classroom, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClass(ctx context.Context, id uuid.UUID) (Classroom, error)
	DeleteClassworkFromClass(ctx context.Context, arg DeleteClassworkFromClassParams) error
	DeleteCommentFromPost(ctx context.Context, arg DeleteCommentFromPostParams) (interface{}, error)
	DeletePostFromClass(ctx context.Context, arg DeletePostFromClassParams) (interface{}, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	GetAllClassFromUser(ctx context.Context, arg GetAllClassFromUserParams) ([]Classroom, error)
	GetAllCommentsFromPost(ctx context.Context, arg GetAllCommentsFromPostParams) ([]Comment, error)
	GetAllFollowers(ctx context.Context, arg GetAllFollowersParams) ([]UserFollow, error)
	GetAllFollowing(ctx context.Context, arg GetAllFollowingParams) ([]UserFollow, error)
	GetClass(ctx context.Context, id uuid.UUID) (Classroom, error)
	GetClassWork(ctx context.Context, arg GetClassWorkParams) (ClassWork, error)
	GetOnePost(ctx context.Context, arg GetOnePostParams) (Post, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context, offset int32) ([]User, error)
	InsertNewClasswork(ctx context.Context, arg InsertNewClassworkParams) (ClassWork, error)
	InsertNewCommentInPost(ctx context.Context, arg InsertNewCommentInPostParams) (Comment, error)
	InsertNewPost(ctx context.Context, arg InsertNewPostParams) (Post, error)
	ListAllPostsByUser(ctx context.Context, arg ListAllPostsByUserParams) ([]Post, error)
	ListAllPostsFromClass(ctx context.Context, arg ListAllPostsFromClassParams) ([]Post, error)
	//description: List all classes
	//parameters: none
	//returns: classes
	ListAllPublicClass(ctx context.Context, offset int32) ([]Classroom, error)
	ListClassworkAdmin(ctx context.Context, arg ListClassworkAdminParams) ([]ClassWork, error)
	ListSubmittedClassworks(ctx context.Context, arg ListSubmittedClassworksParams) ([]ClassWork, error)
	UnfollowUser(ctx context.Context, id uuid.UUID) (UserFollow, error)
	UpdateAClassworkMark(ctx context.Context, arg UpdateAClassworkMarkParams) error
	UpdateClass(ctx context.Context, arg UpdateClassParams) (Classroom, error)
	UpdateCommentContentInPost(ctx context.Context, arg UpdateCommentContentInPostParams) (interface{}, error)
	UpdatePostContent(ctx context.Context, arg UpdatePostContentParams) (interface{}, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
