Enum role {
    STUDENT
    TEACHER
}

Enum visibility {
    PUBLIC
    PRIVATE
}

Table user {
  id uuid [pk]
  username varchar [not null, unique]
  password varchar [not null]
  email varchar [not null, unique]
  user_role role
  visibility visibility 
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table user_follow {
  id uuid [pk, unique]
  follower uuid [not null, ref: > user.id]
  following uuid [not null, ref: > user.id]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table class {
  id uuid [pk, unique]
  admin_id uuid [not null, ref: > user.id]
  name varchar [not null]
  description varchar [not null]
  section varchar [not null]
  room varchar [not null]
  subject varchar [not null]
  invite_code uuid [not null]
  visibility visibility
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table class_work {
  id uuid [pk, unique]
  name varchar [not null]
  user_id uuid [not null, ref: > user.id]
  class_id uuid [not null, ref: > class.id]
  mark int [default: `0`]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table class_member {
  id uuid [pk, unique]
  class_id uuid [not null, ref: > class.id]
  user_id uuid [not null, ref: > user.id]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table post {
  id uuid [pk, unique]
  content varchar [not null]
  author_id uuid [not null, ref: > user.id]
  class_id uuid [not null, ref: > class.id]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table post_like {
  id uuid [pk, unique]
  post_id uuid [not null, ref: > post.id]
  user_id uuid [not null, ref: > user.id]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table comment {
  id uuid [pk]
  content varchar [not null]
  author_id uuid [not null, ref: > user.id]
  post_id uuid [not null, ref: > post.id]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}
