Enum role {
    STUDENT
    TEACHER
}

Table user {
  id uuid [pk]
  username varchar [not null, unique]
  password varchar [not null]
  email varchar [not null, unique]
  user_role role
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table class {
  id uuid [pk, unique]
  admin_id uuid [ref: > user.id]
  name varchar [not null]
  description varchar
  section varchar
  room varchar
  subject varchar
  invite_code uuid
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]

}

Table class_work {
  id uuid [pk, unique]
  name varchar [not null]
  user_id uuid [ref: > user.id]
  class_id uuid [ref: > class.id]
  mark int [default: `0`]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table post {
  id uuid [pk, unique]
  content varchar [not null]
  author_id uuid [ref: > user.id]
  class_id uuid
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}

Table comment {
  id uuid [pk]
  content varchar [not null]
  author_id uuid [ref: > user.id]
  post_id uuid [ref: > post.id]
  created_at timestamptz [default: `now()`]
  updated_at timestamptz [default: `now()`]
}
